[project]
name = "zdo"
version = "0.1.0"
description = "Add `our description here"
readme = "README.md"
authors = [
    { name = "jadevgit", email = "198134441+jadevgit@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
]

[project.scripts]
zdo = "zdo:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
